mvsec:
  outdoor_day1:
    step: 
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    start: 222.4
    stop: 240.4
    test_shape:
      - 256
      - 256
    crop_type: central
    is_car: True
  indoor_flying1:
    step: 
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    start:
    stop:
    test_shape:
      - 256
      - 256
    crop_type: central
    is_car: False
  indoor_flying2:
    step: 
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    start:
    stop:
    test_shape:
      - 256
      - 256
    crop_type: central
    is_car: False
  indoor_flying3:
    step: 
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    start:
    stop:
    test_shape:
      - 256
      - 256
    crop_type: central
    is_car: False
